# -*- coding: utf-8 -*-
"""SYNTECXHUB_DATA_CLEANING_UTILITY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRtlL6ID_jrNqtQXFuQpgLVSZaNezlw2
"""

import pandas as pd

df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn (1).csv')
df

df.info()

df.drop(columns=['customerID'], inplace=True)

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

binary_cols = [
    'gender', 'Partner', 'Dependents', 'PhoneService',
    'PaperlessBilling', 'Churn'
]

for col in binary_cols:
    df[col] = df[col].map({
        'Yes': 1,
        'No': 0,
        'Male': 1,
        'Female': 0
    })

service_cols = [
    'MultipleLines', 'OnlineSecurity', 'OnlineBackup',
    'DeviceProtection', 'TechSupport',
    'StreamingTV', 'StreamingMovies'
]

for col in service_cols:
    df[col] = df[col].replace({
        'No internet service': 'No',
        'No phone service': 'No'
    })
    df[col] = df[col].map({'Yes': 1, 'No': 0})

df = pd.get_dummies(df, drop_first=True)

bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
df[num_cols] = scaler.fit_transform(df[num_cols])

df.info()
df.isnull().sum()

df['TotalCharges'].isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

df

